In [1]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
       SELECT f.name,
SUM(CASE WHEN b.memid = 0 THEN b.slots * f.guestcost 
WHEN b.memid > 0 THEN b.slots * f.membercost 
ELSE 0 END) AS revenue 
FROM Facilities f 
INNER JOIN Bookings b 
ON b.facid = f.facid 
GROUP BY f.name 
HAVING SUM(CASE WHEN b.memid = 0 THEN b.slots * f.guestcost 
 WHEN b.memid > 0 THEN b.slots * f.membercost ELSE 0 END) < 1000;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Pool Table', 270)
('Snooker Table', 240)
('Table Tennis', 180)

In [2]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
      SELECT surname || ', ' || firstname AS full_name,
		(SELECT surname || ', '|| firstname
         FROM Members r
         WHERE m.recommendedby = r.memid) as member_who_recommended
FROM Members m
WHERE m.recommendedby > 0
ORDER BY full_name ;

        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Bader, Florence', 'Stibbons, Ponder')
('Baker, Anne', 'Stibbons, Ponder')
('Baker, Timothy', 'Farrell, Jemima')
('Boothe, Tim', 'Rownam, Tim')
('Butters, Gerald', 'Smith, Darren')
('Coplin, Joan', 'Baker, Timothy')
('Crumpet, Erica', 'Smith, Tracy')
('Dare, Nancy', 'Joplette, Janice')
('Genting, Matthew', 'Butters, Gerald')
('Hunt, John', 'Purview, Millicent')
('Jones, David', 'Joplette, Janice')
('Jones, Douglas', 'Jones, David')
('Joplette, Janice', 'Smith, Darren')
('Mackenzie, Anna', 'Smith, Darren')
('Owen, Charles', 'Smith, Darren')
('Pinker, David', 'Farrell, Jemima')
('Purview, Millicent', 'Smith, Tracy')
('Rumney, Henrietta', 'Genting, Matthew')
('Sarwin, Ramnaresh', 'Bader, Florence')
('Smith, Jack', 'Smith, Darren')
('Stibbons, Ponder', 'Tracy, Burton')
('Worthington-Smyth, Henry', 'Smith, Tracy')

In [3]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
      SELECT f.name, 
(SELECT COUNT(*) 
FROM Bookings b 
WHERE b.facid = f.facid 
AND b.memid > 0) as how_many 
FROM Facilities f;

        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Tennis Court 1', 308)
('Tennis Court 2', 276)
('Badminton Court', 344)
('Table Tennis', 385)
('Massage Room 1', 421)
('Massage Room 2', 27)
('Squash Court', 195)
('Snooker Table', 421)
('Pool Table', 783)

In [4]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
      SELECT SUBSTR(b.starttime, 6, 2) AS month, 
f.name, COUNT(*) AS bookings_count 
FROM Facilities f 
INNER JOIN Bookings b 
	ON b.facid = f.facid 
GROUP BY f.name, month 
ORDER BY month;

        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('07', 'Badminton Court', 56)
('07', 'Massage Room 1', 123)
('07', 'Massage Room 2', 12)
('07', 'Pool Table', 110)
('07', 'Snooker Table', 75)
('07', 'Squash Court', 75)
('07', 'Table Tennis', 51)
('07', 'Tennis Court 1', 88)
('07', 'Tennis Court 2', 68)
('08', 'Badminton Court', 146)
('08', 'Massage Room 1', 224)
('08', 'Massage Room 2', 40)
('08', 'Pool Table', 291)
('08', 'Snooker Table', 159)
('08', 'Squash Court', 170)
('08', 'Table Tennis', 147)
('08', 'Tennis Court 1', 146)
('08', 'Tennis Court 2', 149)
('09', 'Badminton Court', 181)
('09', 'Massage Room 1', 282)
('09', 'Massage Room 2', 59)
('09', 'Pool Table', 435)
('09', 'Snooker Table', 210)
('09', 'Squash Court', 195)
('09', 'Table Tennis', 205)
('09', 'Tennis Court 1', 174)
('09', 'Tennis Court 2', 172)